language: node_js
node_js:
- '0.11'
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_57703ae61a7e_key -iv $encrypted_57703ae61a7e_iv
  -in sanx.github.io.travis.enc -out ~/.ssh/sanx.github.io.travis -d
- chmod u=rw,og= ~/.ssh/sanx.github.io.travis
- echo "Host github.com" >> ~/.ssh/config
- echo "IdentityFile ~/.ssh/sanx.github.io.travis" >> ~/.ssh/config
- git config --global user.email "gerardo@gerardomoad.com"
- git config --global user.name "Gerardo Moad"
deploy:
  provider: script
  script: bin/sanx.github.io-deploy.sh
  on:
    branch: master
